asyml/texar

examples/vae_text/README.md, examples/vae_text/config_lstm_ptb.py, examples/vae_text/config_lstm_yahoo.py, examples/vae_text/config_trans_ptb.py, examples/vae_text/config_trans_yahoo.py, examples/vae_text/vae_train.py
Update VAE training for the latest interface, also rerun experiments and update the results
=> Fix VAE text example when applying transformer

examples/seqgan/seqgan_train.py
Change tf.squeeze() into tf.reshape().
=> Fix dimension error in examples/seqgan/

examples/vae_text/README.md, examples/vae_text/vae_train.py
Add sentence generation feature to vae_text example, and concatenate latent variable to input embeddings for LSTM decoder.
=> Add sentence generation feature to vae_text example

examples/vae_text/config_trans_ptb.py, examples/vae_text/config_trans_yahoo.py
modify configure file in `vae_text` example for new transformer interface
=> modify vae_text example to fit new transformer interface

examples/vae_text/config_trans_ptb.py, texar/modules/decoders/transformer_decoders.py
- Unnecessary backslash removed & typo in docs resolved. 
- fix the issue in examples/vae_train.py
=> Fix issue in examples/vae_train.py and remove unnecessary backslash

examples/vae_text/config_lstm_ptb.py, examples/vae_text/config_lstm_yahoo.py, examples/vae_text/config_trans_ptb.py, examples/vae_text/config_trans_yahoo.py, examples/vae_text/vae_train.py
Write embedder dropout into embedder hparams
=> simplify code in vae_text example

examples/seqgan/README.md, examples/seqgan/seqgan_train.py
This pull request contains the following changes:
(1) Specify variables when optimizing discriminator's pre-train loss and the loss for updating the generator in the adversarial training.
(2) Update README.
=> Specify variables for optimization

examples/transformer/README.md, examples/transformer/transformer_main.py, texar/core/layers.py, texar/modules/decoders/transformer_decoders.py, texar/modules/decoders/transformer_decoders_test.py, texar/modules/encoders/multihead_attention.py, texar/modules/encoders/transformer_encoders.py
=> Add helper to and refactor code of TransformerDecoder

examples/seqgan/seqgan_train.py
Collect the trainable variables for the generator and the discriminator after relevant modules are called.
=> Collect trainable variables after relevant modules are called in seqgan/.

examples/bert/README.md, examples/bert/bert_classifier_main.py, examples/bert/config_data.py, examples/bert/config_data_mrpc.py, examples/bert/config_data_sst.py, examples/bert/prepare_data.py, examples/bert/utils/data_utils.py, texar/data/data/__init__.py, texar/data/data/multi_aligned_data.py, texar/data/data/multi_aligned_data_test.py, texar/data/data/tfrecords_data.py, texar/data/data/tfrecords_data_test.py, texar/data/data_decoders.py
=> Bert add tfrecord module; MultialignedData add tfrecord module

CHANGELOG.md, examples/bert/bert_classifier_main.py, examples/bert/bert_config_lib/config_model_uncased_L-12_H-768_A-12.py, examples/bert/utils/model_utils.py, examples/distributed_gpu/README.md, examples/gpt-2/configs/config_model.py, examples/gpt-2/gpt2_generate_main.py, examples/gpt-2/utils/model_utils.py, examples/transformer/config_model.py, examples/transformer/transformer_main.py, requirements.txt, texar/modules/decoders/__init__.py, texar/modules/decoders/helper.py, texar/modules/decoders/rnn_decoder_base.py, texar/modules/decoders/rnn_decoder_helpers.py, texar/modules/decoders/rnn_decoder_helpers_test.py, texar/modules/decoders/rnn_decoders.py, texar/modules/decoders/rnn_decoders_test.py, texar/modules/decoders/tf_helpers.py, texar/modules/decoders/transformer_decoders.py, texar/modules/decoders/transformer_decoders_test.py, texar/modules/embedders/embedders.py, texar/modules/embedders/position_embedders.py, texar/modules/encoders/transformer_encoders.py, texar/utils/beam_search.py, texar/utils/utils.py
Based on #124, fixed conflicts with other components
=> Refined refactor pos embedding

texar/losses/losses_utils.py
=> update losses_utils.reduce_dimensions 

texar/losses/losses_utils.py
=> cast `sequence_length` base on the type of `sequence`

texar/losses/mle_losses_test.py
=> fix bug in mle_losses_test

texar/losses/pg_losses.py
=> fix bug in pg_loss_with_log_probs

texar/losses/pg_losses.py, texar/losses/pg_losses_test.py
=> Add pg_losses_test in losses folder

texar/utils/transformer_utils.py
Fix building error and retested.
=> Fix minor typos

README.md, texar/version.py
* Restructure README to highlight key features
* Update version to v0.2.3-unreleased
=> Update README and version

CHANGELOG.md, texar/modules/connectors/connectors.py
=> Update Connector docstring

docs/code/utils.rst, texar/tf/utils/shapes.py, texar/tf/utils/shapes_test.py
Add new utils in `texar/tf/utils/shapes.py`
- `reduce_with_weights`
- `varlength_*`
=> Add new shape utils

.travis.yml, docs/code/modules.rst, docs/code/txtgen.rst, docs/requirements.txt, requirements.txt, setup.py, texar/tf/modules/classifiers/bert_classifier.py, texar/tf/modules/classifiers/xlnet_classifier.py, texar/tf/modules/encoders/xlnet_encoder.py, texar/tf/modules/regressors/xlnet_regressor.py
=> Update pre-trained docs

CHANGELOG.md, examples/text_style_transfer/README.md, texar/tf/version.py
* Update version to v0.2.3
* Update CHANGELOG
* Update `examples/text_style_transfer` README
=> Release v0.2.3

texar/tf/core/layers.py, texar/tf/data/tokenizers/__init__.py, texar/tf/data/tokenizers/gpt2_tokenizer.py, texar/tf/data/tokenizers/gpt2_tokenizer_test.py, texar/tf/data/tokenizers/gpt2_tokenizer_utils.py, texar/tf/modules/classifiers/__init__.py, texar/tf/modules/classifiers/gpt2_classifier.py, texar/tf/modules/classifiers/gpt2_classifier_test.py, texar/tf/modules/encoders/__init__.py, texar/tf/modules/encoders/gpt2_encoder.py, texar/tf/modules/encoders/gpt2_encoder_test.py, texar/tf/modules/pretrained/__init__.py, texar/tf/modules/pretrained/gpt2.py, texar/tf/modules/pretrained/gpt2_test.py
This PR includes GPT2Encoder and GPT2Classifier.
=> Add GPT2 modules

css/index.css, index.html, pages/resources.html
- change card button hover to click for description, add a close button
- open blog in new tab
- change description overlay background to be non transparent
- use html instead text for run command (so we can put link in it)
- add copy button to run command
=> website update

examples/transformer/scripts/wmt14_en_de.sh
=> Bugfix in transformer example

texar/tf/data/tokenizers/tokenizer_base.py, texar/tf/data/tokenizers/xlnet_tokenizer_test.py
=> Use warning instead of error in map_token_to_id

index.html
Add up-to-date information for Forte.
=> Update forte information in index.

css/carousel.css, css/index.css, index.html
=> add one more card and adjust style

index.html
[skip ci] fix mailto link in asyml.
=> fix mailto link
